#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
$HOME/.config/polybar/launch.sh
feh --bg-fill $HOME/Pictures/red-flower-branches-1920×1080.jpg
picom --config $HOME/.config/picom/picom.conf &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V


#bspc config border_width         0
bspc config window_gap          20
bspc config border_width 				1
bspc config focused_border_color '#dc143c'
bspc config normal_border_color '#000'

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^5'
bspc rule -a nautilus desktop='^4' focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


